steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'FnGateway',
      '--runtime', 'go111',
      '--trigger-http',
      '--source', './app',
      '--memory', '256MB',
      '--region', 'us-central1',
      '--timeout', '500s',
      '--vpc-connector', 'projects/sotah-prod/locations/us-central1/connectors/sotah-connector'
    ]